name: secure_wipe_app
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^8.0.0+1        
  permission_handler: ^11.3.1   
  pdf: ^3.10.8
  path_provider: ^2.1.3
  share_plus: ^9.0.0            
  open_file: ^3.3.2
  crypto: ^3.0.3
  uuid: ^4.4.0
  intl: ^0.19.0                
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1a1a2e"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/howto/
